version: '3.7'
services:
  spa:
    build:
      context: .
      dockerfile: ./Dockerfile
    command: /bin/sh -c "yarn && yarn run start"
    ports:
      - '80:8080'
    volumes:
      - ./:/app/:cached
